/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class github_jp1017_hellojni_MainActivity */

#ifndef _Included_github_jp1017_hellojni_MainActivity
#define _Included_github_jp1017_hellojni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     github_jp1017_hellojni_MainActivity
 * Method:    staticRegFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_github_jp1017_hellojni_MainActivity_staticRegFromJni
  (JNIEnv *, jobject);

/*
 * Class:     github_jp1017_hellojni_MainActivity
 * Method:    dynamicRegFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_github_jp1017_hellojni_MainActivity_dynamicRegFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
